name: Update grammar files

on:
    schedule:
        - cron: "0 0 * * 2"
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    update-grammar-file:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [21.x]

        steps:
            - uses: actions/checkout@v4
              with:
                  ref: master
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - run: npm ci
            - run: npm run update-grammars
            - name: Get current date
              id: date
              run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
            - uses: peter-evans/create-pull-request@v6
              with:
                  commit-message: "fix: auto-update grammar files (${{ steps.date.outputs.date }})"
                  delete-branch: true
                  title: "fix: auto-update grammar files (${{ steps.date.outputs.date }})"
                  base: master
                  body: |
                      This PR was automatically generated to update the grammar files.
                  branch: ${{ steps.date.outputs.date }}
                  reviewers: Robot-Inventor
